name: "github-action-go"
description: "An example of building github actions with Go"

inputs:
  health_check_url:
    required: true
  slack_token:
    required: true
  slack_channel:
    required: true

runs:
  using: docker
  image: Dockerfile
